### ISSUE TITLE
Add a description to your repo

### ISSUE THREAD

**Issue by LorenzoSapora** [acidjazz/metapi#2]
Hi leather daddy, please add a description to your repo, uwu

**Comment by stancl** [comment]
![Screen Shot 2020-08-13 at 14 49 00](https://user-images.githubusercontent.com/33033094/90136485-85441d80-dd74-11ea-942d-6a466c118031.png)

**Comment by acidjazz** [comment]
lol what do you mean? where? i have one for github and composer @LorenzoSapora @stancl
